services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}-socket
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    networks:
      - app_net

networks:
  app_net:
    external: true
