services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME:-myapp}-api
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    env_file:
      - .env
    networks:
      - ${NETWORK_NAME:-app_net}

networks:
  app_net:
    name: ${NETWORK_NAME:-app_net}
