services:
  redis:
    image: redis:8
    container_name: ${APP_NAME:-myapp}-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    networks:
      - ${NETWORK_NAME:-app_net}

volumes:
  redisdata:

networks:
  app_net:
    name: ${NETWORK_NAME:-app_net}
